### PR TITLE
responsive signin and signup page

### PR DESCRIPTION
**Pull request by EnechukwuChibuike**
Responsive Signin and SignUp Page

[res. signin and signup.zip](https://github.com/rajayush012/sahitya/files/5400073/res.signin.and.signup.zip)

### CODE REVIEW

**Comment by EnechukwuChibuike** [comment]
For the signup page, the image needs to be none for mobile views 
I don't know the source of the image, I would have removed it

**Comment by EnechukwuChibuike** [comment]
For the signup page, I think the image needs to be  none on mobile views
I don't know the source of the image, I would have displayed it none on mobile views

**Review by rajayush012 — APPROVED** [review]

**Comment by rajayush012** [comment]
The changes look good.

Can you attach some screenshots @EnechukwuChibuike showing how the pages look like when the dimensions of the window is changed?

**Comment by rajayush012** [comment]
Looks good!

> Responsive Signin and SignUp Page
> 
> [res. signin and signup.zip](https://github.com/rajayush012/sahitya/files/5400073/res.signin.and.signup.zip)

**Comment by EnechukwuChibuike** [comment]
Please, can you add #hacktoberfest-accepted to this PR
It doesn't count to my progress
Pleaseeee

**Comment by EnechukwuChibuike** [comment]
> Please, can you add #hacktoberfest-accepted to this PR
> It doesn't count to my progress
> Pleaseeee

Also label #Hacktoberfest

**Comment by rajayush012** [comment]
Cool

**Comment by EnechukwuChibuike** [comment]
@rajayush012  Thanks

**Pull request merged**
